---
title: "Assignment1"
output:
  html_document: default
  PDF_document: default
date: "2026-09-13"
---

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.

## Data Set Cereal DataSet
## cereal"https://raw.githubusercontent.com/rfortherestofus/rin3-datasets/main/getting-started-datasets/cereal/cereal.csv"
```{r}

cereal <- read.csv(
  "https://raw.githubusercontent.com/rfortherestofus/rin3-datasets/main/getting-started-datasets/cereal/cereal.csv"
)
```

```{r}
#view first rows
head(cereal)

```

```{r}
#examine variables
str(cereal)

```


```{r}
#descriptive statistics for quantitative variables

summary(cereal$calories)

summary(cereal$protein_g)

summary(cereal$fat_g)

summary(cereal$cups_per_serv)

```


```{r}
# descriptive statistics for categorical variables

table(cereal$mfr)

table(cereal$shelf)

table(cereal$type)

```


```{r}
#Transform 

cereal$high_sugar <- ifelse(
  cereal$sugars >= 10,
  "Yes",
  "No"
)

head(cereal$high_sugar)

table(cereal$high_sugar)

```


```{r}
# quantitative variable plot
hist(
  cereal$calories,
  main = "Distribution of Cereal Calories",
  xlab = "Calories per Serving",
  ylab = "Number of Cereals"
)

```



```{r}
#Qualitative variable plot

plot(
  cereal$sugars,
  cereal$calories,
  main = "Sugar vs. Calories in Cereal",
  xlab = "Sugar (grams)",
  ylab = "Calories",
  
)

```



